--- !ruby/object:VR_ENV
filename: ".vr_settings.yaml"
width: 1251
height: 691
panel_pos: 258
notebook_panel_position: 489
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/listview/main.rb"
- "/home/eric/vrp/vr3/examples/listview/bin/SongListViewGUI.rb"
- "/home/eric/vrp/vr3/examples/listview/bin/SongListView.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/listview"
- "/home/eric/vrp/vr3/examples/listview/bin"
current_file: "/home/eric/vrp/vr3/examples/listview/bin/SongListView.rb"
current_line: -1
rdoc_command_line: rdoc -x README
vr_yaml_file: ".vr_settings.yaml"
