--- !ruby/object:VR_ENV
vr_yaml_file: ".vr_settings.yaml"
width: 1251
height: 691
panel_pos: 322
notebook_panel_position: 437
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/listview/bin/SongListViewGUI.rb"
- "/home/eric/vrp/vr3/examples/listview/main.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/listview"
current_file: "/home/eric/vrp/vr3/examples/listview/main.rb"
current_line: 4
rdoc_command_line: rdoc -x README
filename: ".vr_settings.yaml"
