--- !ruby/object:VR_ENV
width: 1036
height: 677
panel_pos: 360
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/listview/main.rb"
- "/home/eric/vrp/vr3/examples/listview/bin/SongListViewGUI.rb"
- "/home/eric/vrp/vr3/examples/listview/bin/SongListView.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/listview"
- "/home/eric/vrp/vr3/examples/listview/bin"
current_file: "/home/eric/vrp/vr3/examples/listview/bin/SongListView.rb"
rdoc_command_line: rdoc -x README
filename: ".vr_settings.yaml"
notebook_panel_position: 400
current_line: -1
