--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/listview/.vr_settings.yaml"
width: 1301
height: 744
panel_pos: 322
notebook_panel_position: 437
run_command_line: ruby listview.rb
open_files:
- "/home/eric/vrp/vr3/examples/listview/listview.gemspec"
- "/home/eric/vrp/vr3/examples/listview/src/SongListViewGUI.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/listview"
- "/home/eric/vrp/vr3/examples/listview/src"
- "/home/eric/vrp/vr3/examples/listview/src/glade"
current_file: "/home/eric/vrp/vr3/examples/listview/src/SongListViewGUI.rb"
current_line: 43
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
filename: ".vr_settings.yaml"
