--- !ruby/object:VR_ENV
browser: firefox
width: 1858
height: 1003
panel_pos: 360
backup_path: "/home/eric"
tab_spaces: 2
run_command_line: ruby color_cells.rb
open_files:
- "/home/eric/vrp/vr3/examples/76_color_cells/color_cells.rb"
- "/home/eric/vrp/vr3/examples/76_color_cells/src/BalanceListView.rb"
- "/home/eric/vrp/vr3/examples/76_color_cells/src/CurrencyObject.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/76_color_cells"
- "/home/eric/vrp/vr3/examples/76_color_cells/src"
- "/home/eric/vrp/vr3/examples/76_color_cells/src/glade"
current_file: "/home/eric/vrp/vr3/examples/76_color_cells/src/CurrencyObject.rb"
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
vr_yaml_file: "/home/eric/vrp/vr3/examples/76_color_cells/.vr_settings.yaml"
notebook_panel_position: 718
current_line: 1
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
