--- !ruby/object:VR_ENV
settings_file_version: 1
width: 1365
height: 972
panel_pos: 843
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/listview_objects/bin/ListViewObjectsGUI.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/listview_objects"
- "/home/eric/vrp/vr3/examples/listview_objects/bin"
current_file: "/home/eric/vrp/vr3/examples/listview_objects/bin/ListViewObjectsGUI.rb"
rdoc_command_line: rdoc -x README
