--- !ruby/object:VR_ENV
width: 1337
height: 691
panel_pos: 490
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/filetreeview/main.rb"
- "/home/eric/vrp/vr3/examples/filetreeview/bin/MyClass.rb"
- "/home/eric/vrp/vr3/examples/filetreeview/bin/ProjectTree.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/filetreeview"
- "/home/eric/vrp/vr3/examples/filetreeview/bin"
- "/home/eric/vrp/vr3/examples/filetreeview/bin/glade"
current_file: "/home/eric/vrp/vr3/examples/filetreeview/bin/ProjectTree.rb"
rdoc_command_line: rdoc -x README
settings_file_version: 1
filename: ".vr_settings.yaml"
notebook_panel_position: 400
current_line: 12
