--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/filetreeview/.vr_settings.yaml"
width: 1301
height: 744
panel_pos: 490
notebook_panel_position: 400
run_command_line: ruby filetreeview.rb
open_files:
- "/home/eric/vrp/vr3/examples/filetreeview/src/ProjectTreeGUI.rb"
- "/home/eric/vrp/vr3/examples/filetreeview/filetreeview.rb"
- "/home/eric/vrp/vr3/examples/filetreeview/src/ProjectTree.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/filetreeview"
- "/home/eric/vrp/vr3/examples/filetreeview/src"
current_file: "/home/eric/vrp/vr3/examples/filetreeview/src/ProjectTree.rb"
current_line: 22
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
settings_file_version: 1
top_level_window: false
filename: ".vr_settings.yaml"
