--- !ruby/object:VR_ENV
vr_yaml_file: ".vr_settings.yaml"
width: 1364
height: 691
panel_pos: 360
notebook_panel_position: 400
run_command_line: ruby vr
open_files:
- "/home/eric/vrp/vr3/vr.gemspec"
- "/home/eric/vrp/vr3/vr"
- "/home/eric/vrp/vr3/lib/vrlib.rb"
- "/home/eric/vrp/vr3/lib/treeview/columns/ProgressCol.rb"
- "/home/eric/vrp/vr3/src/main/VR_Tools.rb"
- "/home/eric/vrp/vr3/src/main/VR_Main.rb"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/src"
- "/home/eric/vrp/vr3/src/main"
- "/home/eric/vrp/vr3/src/main/glade"
current_file: "/home/eric/vrp/vr3/vr.gemspec"
current_line: 21
rdoc_command_line: yardoc lib - site/*.*
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
