--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 357
notebook_panel_position: 709
run_command_line: ruby vr
open_files:
- "/home/eric/vrp/vr3/vr"
- "/home/eric/vrp/vr3/all_requires.rb"
- "/home/eric/vrp/vr3/src/version.rb"
- "/home/eric/vrp/vr3/vr.gemspec"
- "/home/eric/vrp/vr3/lib/vrlib.rb"
- "/home/eric/vrp/vr3/lib/GladeGUI.rb"
- "/home/eric/vrp/vr3/src/main/VR_File_Tree.rb"
- "/home/eric/vrp/vr3/lib/treeview/FileTreeView.rb"
- "/home/eric/vrp/vr3/lib/treeview/TreeView.rb"
- "/home/eric/vrp/vr3/lib/treeview/ViewCommon.rb"
- "/home/eric/vrp/vr3/lib/Alert.rb"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/lib"
- "/home/eric/vrp/vr3/src"
- "/home/eric/vrp/vr3/src/glade"
- "/home/eric/vrp/vr3/src/main"
current_file: "/home/eric/vrp/vr3/lib/GladeGUI.rb"
current_line: 475
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
