--- !ruby/object:VR_ENV
width: 1455
height: 704
panel_pos: 277
run_command_line: ruby vr
open_files:
- "/home/eric/vrp/vr3/bin/main/GemTree.rb"
- "/home/eric/vrp/vr3/bin/tools/VR_Tools.rb"
- "/home/eric/vrp/vr3/bin/main/VR_File_Tree.rb"
- "/home/eric/vrp/vr3/vrlib/vrlib.gemspec"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/vrlib"
current_file: "/home/eric/vrp/vr3/vrlib/vrlib.gemspec"
rdoc_command_line: rdoc -x README
settings_file_version: 1
filename: ".vr_settings.yaml"
notebook_panel_position: 334
current_line: 17
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
