--- !ruby/object:VR_ENV
filename: ".vr_settings.yaml"
width: 1275
height: 665
panel_pos: 257
notebook_panel_position: 470
run_command_line: ruby vr
open_files:
- "/home/eric/vrp/vr3/vrlib/lib/treeview/columns/TreeViewColumn.rb"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/columns/ComboCol.rb"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/columns/SpinCol.rb"
- "/home/eric/vrp/vr3/README.md"
- "/home/eric/vrp/vr3/vr"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/ViewCommon.rb"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/columns/CellRendererObject.rb"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/columns/CellRendererDate.rb"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/IterMethods.rb"
- "/home/eric/vrp/vr3/bin/editor/VR_Document.rb"
- "/home/eric/vrp/vr3/vrlib/lib/grid/GridCalendar.rb"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/bin"
- "/home/eric/vrp/vr3/examples"
- "/home/eric/vrp/vr3/examples/grid"
- "/home/eric/vrp/vr3/vrlib"
- "/home/eric/vrp/vr3/vrlib/lib"
- "/home/eric/vrp/vr3/vrlib/lib/treeview"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/columns"
current_file: "/home/eric/vrp/vr3/vrlib/lib/grid/GridCalendar.rb"
current_line: 26
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
vr_yaml_file: ".vr_settings.yaml"
