--- !ruby/object:VR_ENV
settings_file_version: 1
width: 1206
height: 600
panel_pos: 362
run_command_line: ruby vr
open_files:
- "/home/eric/vrp/vr3/bin/main/VR_ENV.rb"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/bin"
- "/home/eric/vrp/vr3/bin/main"
current_file: "/home/eric/vrp/vr3/bin/main/VR_ENV.rb"
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
notebook_panel_position: 147
