--- !ruby/object:VR_ENV
width: 1261
height: 691
panel_pos: 360
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/vrlib/doc/VR/CellRendererCombo.html"
- "/home/eric/vrp/vr3/vrlib/lib/Alert.rb"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/vrlib"
- "/home/eric/vrp/vr3/vrlib/lib"
current_file: "/home/eric/vrp/vr3/vrlib/lib/Alert.rb"
rdoc_command_line: yardoc
vr_yaml_file: ".vr_settings.yaml"
notebook_panel_position: 400
current_line: 103
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
