--- !ruby/object:VR_ENV
width: 1364
height: 691
panel_pos: 267
run_command_line: ruby vr
open_files:
- "/home/eric/vrp/vr3/bin/main/GemTree.rb"
- "/home/eric/vrp/vr3/bin/main/VR_File_Tree.rb"
- "/home/eric/vrp/vr3/vr.gemspec"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/IterMethods.rb"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/vrlib"
- "/home/eric/vrp/vr3/vrlib/lib"
current_file: "/home/eric/vrp/vr3/vr.gemspec"
rdoc_command_line: rdoc -x README
settings_file_version: 1
filename: ".vr_settings.yaml"
notebook_panel_position: 482
current_line: 46
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
