--- !ruby/object:VR_ENV
settings_file_version: 1
width: 1491
height: 724
panel_pos: 468
run_command_line: 'ruby vr '
open_files:
- "/home/eric/vrp/vr3/Untitled"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/bin"
- "/home/eric/vrp/vr3/bin/editor"
- "/home/eric/vrp/vr3/bin/main"
- "/home/eric/vrp/vr3/bin/main/glade"
- "/home/eric/vrp/vr3/skeleton"
- "/home/eric/vrp/vr3/vrlib"
- "/home/eric/vrp/vr3/vrlib/lib"
current_file: "/home/eric/vrp/vr3/Untitled"
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
filename: ".vr_settings.yaml"
notebook_panel_position: 507
