--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/.vr_settings.yaml"
width: 1390
height: 826
panel_pos: 351
notebook_panel_position: 506
run_command_line: ruby vr
open_files:
- "/home/eric/vrp/vr3/vr.gemspec"
- "/home/eric/vrp/vr3/lib/treeview/TreeView.rb"
- "/home/eric/vrp/vr3/lib/treeview/ViewCommon.rb"
- "/home/eric/vrp/vr3/lib/treeview/columns/TreeViewColumn.rb"
- "/home/eric/vrp/vr3/lib/treeview/FileTreeView.rb"
- "/home/eric/vrp/vr3/examples/78_listview/src/SongListView.rb"
- "/home/eric/vrp/vr3/examples/71_prettify_view/src/PrettyView.rb"
- "/home/eric/vrp/vr3/lib/GladeGUI.rb"
- "/home/eric/vrp/vr3/README.md"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/lib"
- "/home/eric/vrp/vr3/lib/treeview"
- "/home/eric/vrp/vr3/lib/treeview/columns"
- "/home/eric/vrp/vr3/src"
- "/home/eric/vrp/vr3/src/main"
current_file: "/home/eric/vrp/vr3/README.md"
current_line: 6
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
