--- !ruby/object:VR_ENV
width: 1389
height: 749
panel_pos: 258
run_command_line: ruby vr
open_files:
- "/home/eric/vrp/vr3/bin/main/ProjectTree.rb"
- "/home/eric/vrp/vr3/bin/main/OpenProject.rb"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/FileTreeView.rb"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/ViewCommon.rb"
- "/home/eric/vrp/vr3/bin/main/VR_Main.rb"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/bin"
current_file: "/home/eric/vrp/vr3/bin/main/OpenProject.rb"
rdoc_command_line: rdoc -x README
settings_file_version: 1
filename: ".vr_settings.yaml"
notebook_panel_position: 455
current_line: 61
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
