--- !ruby/object:VR_ENV
width: 1673
height: 847
panel_pos: 360
run_command_line: ruby vr
open_files:
- "/home/eric/vrp/vr3/bin/main/VR_ENV.rb"
- "/home/eric/vrp/vr3/examples/drag_drop/bin/DragDropDemo.rb"
- "/home/eric/vrp/vr3/bin/main/VR_File_Tree.rb"
- "/home/eric/vrp/vr3/bin/main/VR_Local_Gem_Tree.rb"
- "/home/eric/vrp/vr3/bin/main/VR_Remote_Gem_Tree.rb"
- "/home/eric/vrp/vr3/bin/main/GemTree.rb"
- "/home/eric/vrp/vr3/vrlib/lib/Alert.rb"
- "/home/eric/vrp/vr3/bin/main/NewProjectGUI.rb"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/bin"
- "/home/eric/vrp/vr3/bin/main"
- "/home/eric/vrp/vr3/bin/tools"
- "/home/eric/vrp/vr3/vrlib"
- "/home/eric/vrp/vr3/vrlib/lib"
current_file: "/home/eric/vrp/vr3/bin/main/NewProjectGUI.rb"
rdoc_command_line: rdoc -x README
settings_file_version: 1
filename: ".vr_settings.yaml"
notebook_panel_position: 565
current_line: 15
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
