--- !ruby/object:VR_ENV
width: 1364
height: 691
panel_pos: 270
run_command_line: ruby vr
open_files:
- "/home/eric/vrp/vr3/bin/main/NewProjectGUI.rb"
- "/home/eric/vrp/vr3/vrlib/lib/SavableClass.rb"
- "/home/eric/vrp/vr3/bin/main/VR_Main.rb"
- "/home/eric/vrp/vr3/bin/editor/VR_Tabs.rb"
- "/home/eric/vrp/vr3/bin/main/VR_Local_Gem_Tree.rb"
- "/home/eric/vrp/vr3/bin/main/VR_ENV.rb"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/bin"
- "/home/eric/vrp/vr3/bin/editor"
- "/home/eric/vrp/vr3/bin/main"
- "/home/eric/vrp/vr3/examples"
- "/home/eric/vrp/vr3/examples/active_record2"
- "/home/eric/vrp/vr3/examples/active_record2/db"
- "/home/eric/vrp/vr3/vrlib"
- "/home/eric/vrp/vr3/vrlib/lib"
current_file: "/home/eric/vrp/vr3/bin/editor/VR_Tabs.rb"
rdoc_command_line: rdoc -x README -x /*.glade -x /*.yaml -x /*.gemspec -x /*.css
vr_yaml_file: ".vr_settings.yaml"
notebook_panel_position: 474
current_line: 64
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
