--- !ruby/object:VR_ENV
width: 1261
height: 720
panel_pos: 360
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/bin/editor/VR_Document.rb"
- "/home/eric/vrp/vr3/bin/main/VR_Main.rb"
- "/home/eric/vrp/vr3/vrlib/lib/treeview/FileTreeView.rb"
open_folders:
- "/home/eric/vrp/vr3"
- "/home/eric/vrp/vr3/bin"
- "/home/eric/vrp/vr3/bin/main"
current_file: "/home/eric/vrp/vr3/vrlib/lib/treeview/FileTreeView.rb"
rdoc_command_line: rdoc -x README
vr_yaml_file: ".vr_settings.yaml"
notebook_panel_position: 400
current_line: 98
