--- !ruby/object:VR_ENV
vr_yaml_file: ".vr_settings.yaml"
width: 1014
height: 636
panel_pos: 360
notebook_panel_position: 400
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/Untitled"
open_folders:
- "/home/eric/vrp/vr3"
current_file: "/home/eric/vrp/vr3/Untitled"
current_line: -1
rdoc_command_line: rdoc -x README
