#!/usr/bin/env ruby 
#

#don't require rubygems
require "gtksourceview3"
require "yaml" #needed
require "net/http" #needed
require "net/https" #needed
require "find" #needed
require "fileutils" #needed
require "rubygems/installer"
require "rubygems/uninstaller"
require "rubygems/package"
require "rubygems/specification"

#rubygems uses rubygems/package as of ruby 2.0.0
begin
	require "rubygems/builder"
rescue LoadError
end


#make program output in real time so errors visible
STDOUT.sync = true
STDERR.sync = true

my_path = File.expand_path(File.dirname(__FILE__))
if my_path =~ /^\/home\/eric\/vrp\/.*/  
	require File.expand_path(my_path + "/../vrlib3") + "/vrlib.rb"  
else
	require "vrlib"
end

require_all Dir.glob(my_path + "/bin/**/*.rb") # cant require_all root because .rb files in root will run????


VR_Main.new(ARGV).show


