#!/ruby

require "gtk3"
require "gtksourceview3"

require_relative "src/main/SplashWindow"

$root = File.dirname(__FILE__)

main = Gtk::Application.new()
  main.signal_connect "activate" do |app|
    splash = SplashWindow.new()
# #     splash.show_all
# #     splash.set_keep_above(true)
#     splash.show_all
#     splash.hide
#     splash.visible = true
#     splash.show_all
#     while (Gtk.events_pending?)
#       Gtk.main_iteration
#     end
    require_relative "all_requires"
    VR_Main.new(ARGV,splash).show_glade()
  end
main.run 



# @splash = Gtk::Window.new()
# @splash.decorated = false
# img = Gtk::Image.new(file: File.join($root, "img", "splash.png"))
# img.visible = true
# @splash.set_child(img)
# #@splash.set_position(:center)
# #@splash.show_all
# #@splash.position = :center_always
# @splash.show()


# GLib::Timeout.add(40) {
#     while (Gtk.events_pending?)
#       Gtk.main_iteration
#     end     
#     load_everything 
# }
# 
# Gtk.main


