--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/06_builder_variable/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 718
run_command_line: ruby builder.rb
open_files:
- "/home/eric/vrp/vr3/examples/06_builder_variable/README.txt"
- "/home/eric/vrp/vr3/examples/06_builder_variable/src/BuilderDemo.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/06_builder_variable"
- "/home/eric/vrp/vr3/examples/06_builder_variable/src"
- "/home/eric/vrp/vr3/examples/06_builder_variable/src/glade"
current_file: "/home/eric/vrp/vr3/examples/06_builder_variable/src/BuilderDemo.rb"
current_line: 17
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
