--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/07_event_handlers/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 553
run_command_line: ruby event_handlers.rb
open_files:
- "/home/eric/vrp/vr3/examples/07_event_handlers/event_handlers.rb"
- "/home/eric/vrp/vr3/examples/07_event_handlers/src/MyTextView.rb"
- "/home/eric/vrp/vr3/examples/07_event_handlers/src/Event_Handlers.rb"
- "/home/eric/vrp/vr3/examples/07_event_handlers/README.txt"
open_folders:
- "/home/eric/vrp/vr3/examples/07_event_handlers"
- "/home/eric/vrp/vr3/examples/07_event_handlers/src"
- "/home/eric/vrp/vr3/examples/07_event_handlers/src/glade"
current_file: "/home/eric/vrp/vr3/examples/07_event_handlers/src/Event_Handlers.rb"
current_line: 1
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
