--- !ruby/object:VR_ENV
width: 1366
height: 692
panel_pos: 490
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/simple_ruby_gui/bin/DataObjectGUI.rb"
- "/home/eric/vrp/vr3/examples/simple_ruby_gui/main.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/simple_ruby_gui"
- "/home/eric/vrp/vr3/examples/simple_ruby_gui/bin"
- "/home/eric/vrp/vr3/examples/simple_ruby_gui/bin/glade"
current_file: "/home/eric/vrp/vr3/examples/simple_ruby_gui/main.rb"
rdoc_command_line: rdoc -x README
vr_yaml_file: ".vr_settings.yaml"
notebook_panel_position: 400
current_line: 13
settings_file_version: 1
builder: !ruby/object:Gtk::Builder {}
filename: ".vr_settings.yaml"
