--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/70_better_views/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 718
run_command_line: better_views.rb
open_files:
- "/home/eric/vrp/vr3/examples/70_better_views/README.txt"
- "/home/eric/vrp/vr3/examples/70_better_views/better_views.rb"
- "/home/eric/vrp/vr3/examples/70_better_views/src/BetterView.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/70_better_views"
- "/home/eric/vrp/vr3/examples/70_better_views/src"
- "/home/eric/vrp/vr3/examples/70_better_views/src/glade"
current_file: "/home/eric/vrp/vr3/examples/70_better_views/src/BetterView.rb"
current_line: 9
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder
  top_level_window: false
top_level_window: false
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
