--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/03_get_glade_variables/.vr_settings.yaml"
width: 1858
height: 1003
panel_pos: 490
notebook_panel_position: 708
run_command_line: ruby get_glade_variables.rb
open_files:
- "/home/eric/vrp/vr3/examples/03_get_glade_variables/Untitled"
open_folders:
- "/home/eric/vrp/vr3/examples/03_get_glade_variables"
- "/home/eric/vrp/vr3/examples/03_get_glade_variables/src"
- "/home/eric/vrp/vr3/examples/03_get_glade_variables/src/glade"
current_file: "/home/eric/vrp/vr3/examples/03_get_glade_variables/Untitled"
current_line: 1
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
settings_file_version: 1
filename: ".vr_settings.yaml"
top_level_window: false
