--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/drag_drop/.vr_settings.yaml"
width: 1307
height: 698
panel_pos: 423
notebook_panel_position: 400
run_command_line: ruby drag_drop.rb
open_files:
- "/home/eric/vrp/vr3/examples/drag_drop/src/DragDropDemo.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/drag_drop"
- "/home/eric/vrp/vr3/examples/drag_drop/bin"
- "/home/eric/vrp/vr3/examples/drag_drop/bin/glade"
current_file: "/home/eric/vrp/vr3/examples/drag_drop/src/DragDropDemo.rb"
current_line: 4
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
settings_file_version: 1
top_level_window: false
