--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/04_before_show/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 410
run_command_line: before_show.rb
open_files:
- "/home/eric/vrp/vr3/examples/04_before_show/README.txt"
open_folders:
- "/home/eric/vrp/vr3/examples/04_before_show"
current_file: "/home/eric/vrp/vr3/examples/04_before_show/README.txt"
current_line: 9
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
