--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/06_alert_box/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 362
notebook_panel_position: 501
run_command_line: alertdemo.rb
open_files:
- "/home/eric/vrp/vr3/examples/06_alert_box/README.txt"
- "/home/eric/vrp/vr3/examples/06_alert_box/alertdemo.rb"
- "/home/eric/vrp/vr3/examples/06_alert_box/src/AlertBoxDemo.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/06_alert_box"
- "/home/eric/vrp/vr3/examples/06_alert_box/src"
current_file: "/home/eric/vrp/vr3/examples/06_alert_box/src/AlertBoxDemo.rb"
current_line: 57
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
