--- !ruby/object:VR_ENV
settings_file_version: 1
width: 1084
height: 754
panel_pos: 437
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/visualruby_examples/child_window/bin/ChildWindowDemo.rb"
- "/home/eric/vrp/vr3/visualruby_examples/child_window/main.rb"
- "/home/eric/vrp/vr3/visualruby_examples/child_window/bin/MyChildClass.rb"
open_folders:
- "/home/eric/vrp/vr3/visualruby_examples/child_window"
- "/home/eric/vrp/vr3/visualruby_examples/child_window/bin"
- "/home/eric/vrp/vr3/visualruby_examples/child_window/bin/glade"
current_file: "/home/eric/vrp/vr3/visualruby_examples/child_window/main.rb"
rdoc_command_line: rdoc -x README
