--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/child_window/.vr_settings.yaml"
width: 1097
height: 691
panel_pos: 437
notebook_panel_position: 400
run_command_line: ruby child_window.rb
open_files:
- "/home/eric/vrp/vr3/examples/child_window/src/ChildWindowDemo.rb"
- "/home/eric/vrp/vr3/examples/child_window/main.rb"
- "/home/eric/vrp/vr3/examples/child_window/child_window.rb"
- "/home/eric/vrp/vr3/examples/child_window/src/ModalWindow.rb"
- "/home/eric/vrp/vr3/examples/child_window/src/MyChildClass.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/child_window"
- "/home/eric/vrp/vr3/examples/child_window/src"
current_file: "/home/eric/vrp/vr3/examples/child_window/src/ChildWindowDemo.rb"
current_line: 30
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
settings_file_version: 1
