--- !ruby/object:VR_ENV
settings_file_version: 1
width: 1411
height: 777
panel_pos: 490
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/visualruby_examples/simple_ruby_gui/main.rb"
- "/home/eric/vrp/vr3/visualruby_examples/simple_ruby_gui/bin/DataObjectGUI.rb"
open_folders:
- "/home/eric/vrp/vr3/visualruby_examples/simple_ruby_gui"
- "/home/eric/vrp/vr3/visualruby_examples/simple_ruby_gui/bin"
- "/home/eric/vrp/vr3/visualruby_examples/simple_ruby_gui/bin/glade"
current_file: "/home/eric/vrp/vr3/visualruby_examples/simple_ruby_gui/main.rb"
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
