--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/10_all_widgets/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 327
notebook_panel_position: 682
run_command_line: all_widgets.rb
open_files:
- "/home/eric/vrp/vr3/examples/10_all_widgets/README.txt"
- "/home/eric/vrp/vr3/examples/10_all_widgets/all_widgets.rb"
- "/home/eric/vrp/vr3/examples/10_all_widgets/src/AllWidgets.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/10_all_widgets"
- "/home/eric/vrp/vr3/examples/10_all_widgets/src"
current_file: "/home/eric/vrp/vr3/examples/10_all_widgets/src/AllWidgets.rb"
current_line: 37
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
settings_file_version: 1
