--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/49_settings_file/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 580
run_command_line: save_settings.rb
open_files:
- "/home/eric/vrp/vr3/examples/49_settings_file/save_settings.rb"
- "/home/eric/vrp/vr3/examples/49_settings_file/src/SavableSettings.rb"
- "/home/eric/vrp/vr3/examples/49_settings_file/README.txt"
open_folders:
- "/home/eric/vrp/vr3/examples/49_settings_file"
- "/home/eric/vrp/vr3/examples/49_settings_file/src"
current_file: "/home/eric/vrp/vr3/examples/49_settings_file/README.txt"
current_line: 27
rdoc_command_line: rdoc -x README
