--- !ruby/object:VR_ENV
width: 1641
height: 718
panel_pos: 360
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/active_record/Untitled"
open_folders:
- "/home/eric/vrp/vr3/examples/active_record2"
current_file: "/home/eric/vrp/vr3/examples/active_record/Untitled"
rdoc_command_line: rdoc -x README
settings_file_version: 1
filename: ".vr_settings.yaml"
notebook_panel_position: 400
current_line: -1
builder: !ruby/object:Gtk::Builder {}
