--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/treeview/.vr_settings.yaml"
width: 1301
height: 744
panel_pos: 491
notebook_panel_position: 400
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/treeview/main.rb"
- "/home/eric/vrp/vr3/examples/treeview/bin/MyClass.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/treeview"
- "/home/eric/vrp/vr3/examples/treeview/bin"
current_file: "/home/eric/vrp/vr3/examples/treeview/bin/MyClass.rb"
current_line: 1
rdoc_command_line: rdoc -x README
settings_file_version: 1
