--- !ruby/object:VR_ENV
settings_file_version: 1
width: 984
height: 711
panel_pos: 491
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/visualruby_examples/treeview/bin/MyClass.rb"
- "/home/eric/vrp/vr3/visualruby_examples/treeview/main.rb"
open_folders:
- "/home/eric/vrp/vr3/visualruby_examples/treeview"
- "/home/eric/vrp/vr3/visualruby_examples/treeview/bin"
- "/home/eric/vrp/vr3/visualruby_examples/treeview/bin/glade"
current_file: "/home/eric/vrp/vr3/visualruby_examples/treeview/main.rb"
rdoc_command_line: rdoc -x README
