--- !ruby/object:VR_ENV
settings_file_version: 1
width: 1307
height: 698
panel_pos: 423
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/visualruby_examples/drag_drop/bin/DragDropDemo.rb"
- "/home/eric/vrp/vr3/visualruby_examples/drag_drop/main.rb"
open_folders:
- "/home/eric/vrp/vr3/visualruby_examples/drag_drop"
- "/home/eric/vrp/vr3/visualruby_examples/drag_drop/bin"
- "/home/eric/vrp/vr3/visualruby_examples/drag_drop/bin/glade"
- "/home/eric/vrp/vr3/visualruby_examples/drag_drop/img"
current_file: "/home/eric/vrp/vr3/visualruby_examples/drag_drop/bin/DragDropDemo.rb"
rdoc_command_line: rdoc -x README
