--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/05_menus/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 671
run_command_line: menus.rb
open_files:
- "/home/eric/vrp/vr3/examples/05_menus/menus.rb"
- "/home/eric/vrp/vr3/examples/05_menus/src/Menus.rb"
- "/home/eric/vrp/vr3/examples/05_menus/README.txt"
open_folders:
- "/home/eric/vrp/vr3/examples/05_menus"
- "/home/eric/vrp/vr3/examples/05_menus/src"
current_file: "/home/eric/vrp/vr3/examples/05_menus/README.txt"
current_line: 37
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
