--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/alert_box/.vr_settings.yaml"
width: 1366
height: 706
panel_pos: 360
notebook_panel_position: 400
run_command_line: ruby alertdemo.rb
open_files:
- "/home/eric/vrp/vr3/examples/alert_box/alertdemo.rb"
- "/home/eric/vrp/vr3/examples/alert_box/src/AlertBoxDemo.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/alert_box"
- "/home/eric/vrp/vr3/examples/alert_box/src"
- "/home/eric/vrp/vr3/examples/alert_box/src/glade"
current_file: "/home/eric/vrp/vr3/examples/alert_box/src/AlertBoxDemo.rb"
current_line: 84
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
