--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/alert_box/.vr_settings.yaml"
width: 800
height: 600
panel_pos: 360
notebook_panel_position: 400
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/alert_box/main.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/alert_box"
current_file: "/home/eric/vrp/vr3/examples/alert_box/main.rb"
current_line: 8
rdoc_command_line: rdoc -x README
