#!/usr/bin/ruby

require "vrlib"

# from require_all gem:
require_rel 'src/'

last_file = Dir.glob(File.expand_path("~/visualruby/golf_handicap/*.yaml")).max_by {|f| File.mtime(f)}

if File.exist?(last_file)
  VR::load_yaml(Handicap, last_file).show_glade
else
  load_new_golfer
end





