--- !ruby/object:VR_ENV
browser: firefox
width: 1858
height: 1003
panel_pos: 360
backup_path: "/home/eric"
tab_spaces: 2
run_command_line: ruby object_views.rb
open_files:
- "/home/eric/vrp/vr3/examples/72_object_views/src/BalanceListView.rb"
- "/home/eric/vrp/vr3/examples/72_object_views/object_views.rb"
- "/home/eric/vrp/vr3/examples/72_object_views/src/BalanceClass.rb"
- "/home/eric/vrp/vr3/examples/72_object_views/src/CustomerClass.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/72_object_views"
- "/home/eric/vrp/vr3/examples/72_object_views/src"
current_file: "/home/eric/vrp/vr3/examples/72_object_views/src/BalanceClass.rb"
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
vr_yaml_file: "/home/eric/vrp/vr3/examples/72_object_views/.vr_settings.yaml"
notebook_panel_position: 718
current_line: 22
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
