--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/72_object_views/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 718
run_command_line: ruby object_views.rb
open_files:
- "/home/eric/vrp/vr3/examples/72_object_views/src/BalanceListView.rb"
- "/home/eric/vrp/vr3/examples/72_object_views/object_views.rb"
- "/home/eric/vrp/vr3/examples/72_object_views/src/BalanceClass.rb"
- "/home/eric/vrp/vr3/examples/72_object_views/src/CustomerClass.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/72_object_views"
- "/home/eric/vrp/vr3/examples/72_object_views/src"
current_file: "/home/eric/vrp/vr3/examples/72_object_views/src/BalanceClass.rb"
current_line: 12
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
