--- !ruby/object:VR_ENV
browser: firefox
width: 1858
height: 1003
panel_pos: 360
backup_path: "/home/eric"
tab_spaces: 2
run_command_line: ruby prettify_view.rb
open_files:
- "/home/eric/vrp/vr3/examples/78_prettify_view/prettify_view.rb"
- "/home/eric/vrp/vr3/examples/78_prettify_view/src/PrettyView.rb"
- "/home/eric/vrp/vr3/examples/78_prettify_view/README.txt"
open_folders:
- "/home/eric/vrp/vr3/examples/78_prettify_view"
- "/home/eric/vrp/vr3/examples/78_prettify_view/src"
- "/home/eric/vrp/vr3/examples/78_prettify_view/src/glade"
current_file: "/home/eric/vrp/vr3/examples/78_prettify_view/src/PrettyView.rb"
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
vr_yaml_file: "/home/eric/vrp/vr3/examples/78_prettify_view/.vr_settings.yaml"
notebook_panel_position: 553
current_line: 35
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
