--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/02_hello/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 724
run_command_line: ruby hello.rb
open_files:
- "/home/eric/vrp/vr3/examples/02_hello/README.txt"
- "/home/eric/vrp/vr3/examples/02_hello/hello.rb"
- "/home/eric/vrp/vr3/examples/02_hello/src/HelloGUI.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/02_hello"
- "/home/eric/vrp/vr3/examples/02_hello/src"
- "/home/eric/vrp/vr3/examples/02_hello/src/glade"
current_file: "/home/eric/vrp/vr3/examples/02_hello/README.txt"
current_line: 24
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
