--- !ruby/object:VR_ENV
browser: firefox
width: 1858
height: 1003
panel_pos: 360
backup_path: "/home/eric"
tab_spaces: 2
run_command_line: ruby interrupt_exit.rb
open_files:
- "/home/eric/vrp/vr3/examples/67_interrupt_exit/src/InterruptExit.rb"
- "/home/eric/vrp/vr3/examples/67_interrupt_exit/interrupt_exit.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/67_interrupt_exit"
- "/home/eric/vrp/vr3/examples/67_interrupt_exit/src"
- "/home/eric/vrp/vr3/examples/67_interrupt_exit/src/glade"
current_file: "/home/eric/vrp/vr3/examples/67_interrupt_exit/src/InterruptExit.rb"
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
vr_yaml_file: "/home/eric/vrp/vr3/examples/67_interrupt_exit/.vr_settings.yaml"
notebook_panel_position: 622
current_line: 9
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
