--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/97_active_record2/.vr_settings.yaml"
width: 1854
height: 1040
panel_pos: 360
notebook_panel_position: 400
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/97_active_record2/Untitled"
open_folders: []
current_file: "/home/eric/vrp/vr3/examples/97_active_record2/Untitled"
current_line: 1
builder: !ruby/object:Gtk::Builder {}
rdoc_command_line: rdoc -x README
filename: ".vr_settings.yaml"
settings_file_version: 1
