--- !ruby/object:VR_ENV
width: 1307
height: 698
panel_pos: 423
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/vr3/examples/drag_drop/bin/DragDropDemo.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/drag_drop"
- "/home/eric/vrp/vr3/examples/drag_drop/bin"
current_file: "/home/eric/vrp/vr3/examples/drag_drop/bin/DragDropDemo.rb"
rdoc_command_line: rdoc -x README
vr_yaml_file: ".vr_settings.yaml"
notebook_panel_position: 400
current_line: 12
settings_file_version: 1
