--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/03_menus/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 671
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/03_menus/src/Menus.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/03_menus"
- "/home/eric/vrp/vr3/examples/03_menus/src"
- "/home/eric/vrp/vr3/examples/03_menus/src/glade"
current_file: "/home/eric/vrp/03_menus/src/Menus.rb"
current_line: 27
rdoc_command_line: rdoc -x README
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
