--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/active_record/.vr_settings.yaml"
width: 1858
height: 1003
panel_pos: 360
notebook_panel_position: 400
run_command_line: ruby active_record.rb
open_files:
- "/home/eric/vrp/vr3/examples/active_record/Untitled"
open_folders:
- "/home/eric/vrp/vr3/examples/active_record"
- "/home/eric/vrp/vr3/examples/active_record/bin"
- "/home/eric/vrp/vr3/examples/active_record/bin/glade"
current_file: "/home/eric/vrp/vr3/examples/active_record/Untitled"
current_line: 1
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
