--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/92_standalone_exe/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 642
run_command_line: my_program
open_files:
- "/home/eric/vrp/vr3/examples/92_standalone_exe/README.txt"
- "/home/eric/vrp/vr3/examples/92_standalone_exe/my_program"
- "/home/eric/vrp/vr3/examples/92_standalone_exe/src/MyClass.rb"
open_folders:
- "/home/eric/vrp/vr3/examples/92_standalone_exe"
current_file: "/home/eric/vrp/vr3/examples/92_standalone_exe/README.txt"
current_line: 39
