--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/vr3/examples/94_standalone_exe/.vr_settings.yaml"
width: 1854
height: 1003
panel_pos: 360
notebook_panel_position: 300
run_command_line: testy
open_files:
- "/home/eric/vrp/vr3/examples/94_standalone_exe/testy"
- "/home/eric/vrp/vr3/examples/94_standalone_exe/94_standalone_exe.gemspec"
open_folders:
- "/home/eric/vrp/vr3/examples/94_standalone_exe"
current_file: "/home/eric/vrp/vr3/examples/94_standalone_exe/94_standalone_exe.gemspec"
current_line: 16
